grammar org.example.domainmodel.Domainmodel with
                                      org.eclipse.xtext.common.Terminals

generate domainmodel "http://www.example.org/domainmodel/Domainmodel"

Domainmodel :
    (elements+=Type)*;

Type:
    DataType | Entity | COMMENT;

DataType:
    'datatype' ID;

Entity:
    'entity' ID  '{'
        (features+=Feature)*
    '}';

Feature:
     ID ':' DataType;